# This workflow will be run manually
# This workflow is a pre-release step and updates the readme and
# removes SNAPSHOT suffix from version in gradle properties file
name: Pre Release Step
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name : Prepare Release - Update README and remove SNAPSHOT suffix
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Modify the gradle properties file to remove the SNAPSHOT
      run: |
        sed -i -E "s/\(version \= .*\)-SNAPSHOT/\1/g" gradle.properties
    
    - name: Update README file and Commit Release Version
      run: |
        ./gradlew updateReadme
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -am "Update README and Remove SNAPSHOT suffix"
        git push